### ISSUE TITLE
Speech to text conversion branch issue

### ISSUE THREAD

**Issue by aliazmi68** [dice-group/ida#133]
@nikit91 The branch of speech to text conversion was merged in master and then reverted back due to build failure.
https://github.com/dice-group/ida/pull/95
https://github.com/dice-group/ida/pull/130
Now the branch is deleted. Should I restrore branch and raise a pull request from that branch again?

**Comment by nikit91** [comment]
Hi @aliazmi68,
why the branch has been deleted?

**Comment by aliazmi68** [comment]
Hello @nikit91 sorry for late reply. The branch was deleted by Clemens accidentally, but we resolved that issue after discussion. 
I have tested it again throughly and pushed the commit. I can create a new pull request again.
