### ISSUE TITLE
Scikit Data-Dump Correction

### ISSUE THREAD

**Issue by nikit91** [dice-group/ida#37]
The existing format in Scikit Data-Dump for Functions have a field named: "funcParamBody" which carries the information about all the parameters of the function in a single string.

As a user it is very difficult to extract the parameter names, types and description correctly from the single string. (Since, the strings do not follow a single pattern that can uniquely identify different parts)

It would be Ideal if the structure of the value for "funcParamBody" could be something like this:
funcParamBody: [{paramName: 'n_clusters', type: ['int'], optional: false, desc: '.....'}, {....}, {....}]

Also, following are some points I would like to raise about the existing data dump:
1. For the function "spectral_clustering" the value for "allFuncParams" is ["affinity", "Must be symmetric", "n_clusters", "n_components", "eigen_solver", "random_state", "n_init", "eigen_tol", "assign_labels"]
Here the string "Must be symmetric" seems to be wrongly placed inside the function params.

2. Some of the types of the functions is mentioned inside curly braces ("{auto, True, False}"), If they are constants and not types then a separate field should be introduced in "funcParamBody" e.g constvals: ["auto", "True", "False"]

**Comment by rrichajalota** [comment]
@nikit91 can you please mention an example of a function which has its type mentioned inside curly braces?

**Comment by nikit91** [comment]
@rrichajalota 
You can find one inside KMeans:

"funcName": "KMeans",
"funcParamBody": "... init : {k-means++, random or an ndarray} .."

**Comment by nikit91** [comment]
Added as part of milestones for WS18-19.
