### ISSUE TITLE
Frontend Vulnerabilities

### ISSUE THREAD

**Issue by nikit91** [dice-group/ida#66]
Fix needed for the vulnerabilities listed by github for IDA:
https://github.com/dice-group/ida/network/alerts

**Comment by nikit91** [comment]
@maqboolkhan the link probably requires certain access privileges. I have granted you a higher privilege, could you please check now and confirm?

**Comment by maqboolkhan** [comment]
Thanks now i can see it

**Comment by maqboolkhan** [comment]
PR: https://github.com/dice-group/ida/pull/144

**Comment by Cortys** [comment]
Fixed via #144
