### ISSUE TITLE
SessionMap used inside DataDumpUtil.getClusterAlgoParams

### ISSUE THREAD

**Issue by nil9** [dice-group/ida#69]
Facing "Scope 'session' is not active for the current thread;" error while writing test cases for DataDumpUtil.getClusterAlgoParams method.

**Comment by nikit91** [comment]
Hi @faisal07m,

I checked the git history of the method and it looks like you have added a statement accessing the sessionMap inside the aforementioned method.

The method belongs to a util class and ideally it should not really access the sessionMap.

Could please try to move that statement from there?

**Comment by faisal07m** [comment]
Hi @nikit91,
I will solve the problem. 
Thank you for stating  the issue.

**Comment by nikit91** [comment]
Hi @nil9,
The issue has been addressed. Could you please try to take a pull request to your branch from master and confirm if it is solved?

**Comment by nil9** [comment]
Okay

**Comment by nikit91** [comment]
This issue has been resolved.
