### ISSUE TITLE
Data Type exception handling issues

### ISSUE THREAD

**Issue by nil9** [dice-group/ida#86]
For correctTypeValuesTest() method, when correct parameter type is not passed our test, fails as expected but it should throw proper exception message.

**Comment by nikit91** [comment]
@nil9 please provide the full signature of the method. Also, please share the details of the exception

**Comment by nil9** [comment]
upb.ida.util.GetCorrectParamTypes -----this is the intended signature.

**Comment by nikit91** [comment]
@nil9 Please write the steps to replicate the error you faced. (you can also use screenshots to demonstrate)

**Comment by nil9** [comment]
okay

**Comment by nil9** [comment]
resolved
