### ISSUE TITLE
Connection refused: connect http://131.234.28.84:8889/cluster

### ISSUE THREAD

**Issue by nil9** [dice-group/ida#87]
I could not connect to the above server while testing for clustrering.

**Comment by faisal07m** [comment]
Hi,
@nil9  You are having this issue while running a test case?

**Comment by nil9** [comment]
No I am having this issue for running the program itself.

**Comment by nikit91** [comment]
@nil9 @faisal07m 
Has this issue been fixed?

**Comment by faisal07m** [comment]
Hi @nikit91,
I am not sure about what Nilanjan is trying to achieve here. 
Maybe the port(8889) of remote host is not open for the outside world.

**Comment by nikit91** [comment]
@faisal07m 
The port should be open since I requested that in the beginning. Maybe, to test you can try deploying a normal tomcat server at that port after killing the jupyter python kernel process.

**Comment by nil9** [comment]
@faisal07m  any update on this issue?

**Comment by nil9** [comment]
Error resolved
